[project]
name = "mcp-mariadb-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncmy>=0.2.10",
    "fastmcp[cli]>=2.2.8",
    "openai>=1.78.1",
    "python-dotenv>=1.1.0"
]
